# Generated by Django 4.2.5 on 2023-10-07 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_reservation_date_reservation_end_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
