# Generated by Django 4.2.5 on 2023-10-12 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='table',
        ),
        migrations.RemoveField(
            model_name='tables',
            name='restaurant',
        ),
        migrations.DeleteModel(
            name='Hours',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
        migrations.DeleteModel(
            name='Restaurant',
        ),
        migrations.DeleteModel(
            name='Tables',
        ),
    ]
