# Generated by Django 4.2.5 on 2023-10-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tables',
            name='table_nr',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
