# Generated by Django 4.2.5 on 2023-10-12 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_alter_tables_table_nr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tables',
            old_name='table_nr',
            new_name='name',
        ),
    ]
