# Generated by Django 4.2.5 on 2023-10-12 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0010_alter_reservation_guest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='participants',
            field=models.IntegerField(),
        ),
    ]
