# Generated by Django 4.2.5 on 2023-10-12 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0011_alter_reservation_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='end_hour',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='start_hour',
        ),
    ]
